### ISSUE TITLE
大佬，你的插件是我的大救星！

### ISSUE THREAD

**Issue by VictoryLuode** [Trantor2098/hot_node#1]
大佬，想问你需不需要用户反馈？

我是做Blender CG动画的，自从你传了插件我就开始关注了，如果你有兴趣，可以长联系，我可以站在项目生产的角度经常跟你提建议

Email：victoryluode@outlook.com

**Comment by Trantor2098** [comment]
谢谢认可！需要的！
我B站之前就关注了你哦，你的动画我也很崇拜！！
可以随时联系我，深入交流！
Email: Trantor2098@163.com
Blilbili：川陀Trantor
其他私人联系方式，如果你有意向加，也可以邮箱发给我~！
