### ISSUE TITLE
HotNode fails to install through Extensions Interface

### ISSUE THREAD

**Issue by Kovadon** [Trantor2098/hot_node#2]
[WinError 3] The system cannot find the path specified: 'C:\\Users\\*********\\AppData\\Local\\Temp\\hot_node_autosave'

**Comment by Kovadon** [comment]
Fixed by manually creating a folder called 'hot_node_autosave' in the path 'C:\Users\*********\AppData\Local\Temp\'

**Comment by Trantor2098** [comment]
Hi Kovadon, can you tell me if the original error info is " ****** " or it's you covered it for privacy? Thanks!

**Comment by Kovadon** [comment]
I covered it for privacy

**Comment by Trantor2098** [comment]
OK I will soon publish 0.3.1 to fix that... Thanks again for reporting!
