### ISSUE TITLE
Warning - Blender 4.3 

### ISSUE THREAD

**Issue by BennyGovaerts** [Trantor2098/hot_node#4]
![image](https://github.com/user-attachments/assets/b4f3a7d9-33eb-4faf-a03b-abd7f946b295)

**Comment by Trantor2098** [comment]
Hi BennyGovaerts, this warning does not seem to come from the Hot Node, because it did not define a `Editor_PT_LayoutPanel` class. Maybe it's from the other add-on. Btw, this kind of warning can be ignored by usual.

If you have any other questions, welcome to comment.

**Comment by BennyGovaerts** [comment]
![image](https://github.com/user-attachments/assets/493ac63d-ca19-490d-8a85-49e1166e53cb)

**Comment by BennyGovaerts** [comment]
The node group works fine - i get just a warning with blender 4.3

**Comment by BennyGovaerts** [comment]
Test file : if i addthis nodegroup to hotnode preset and load it again i get this warning [Random input selector_.zip](https://github.com/user-attachments/files/17557898/Random.input.selector_.zip)

**Comment by Trantor2098** [comment]
Thanks for the test file, I reoccured this. I will comment here if the bug fixing got any progress. ( •̀ ω •́ )✧

**Comment by Trantor2098** [comment]
Fixed. Reason: Node `Node Reroute`'s some useless values are recorded by Hot Node.
0.7.3 will be pushed to blender hours later to fix that.

**Comment by BennyGovaerts** [comment]
Excellent , works fine with the new update 
Thanks .
