### ISSUE TITLE
Prevent the creation of a preset if no node is selected first

### ISSUE THREAD

**Issue by xan2622** [Trantor2098/hot_node#7]
Blender version: 4.2.3
Add-on version: 0.7.4

It seems possible to create an (empty) preset even if no nodes are selected. 

Steps to reproduce this behavior:
1. Create a pack
2. Click on an empty area of the Node Editor (to make sure no node is selected)
3. Click on the "+" icon to add a preset
4. Click on 'Get' button (obviously, it does nothing, which is normal)

But IMO, it shouldn't be possible to create a preset if no node is selected.

**Comment by Trantor2098** [comment]
You do have a point, at least we should give a modeless warning to tell users the preset is empty, for enhancing UX. 

I followed the logic of blender's VertexGroup creating when design this, for keeping the consistency of UX - they allow users to create even there is no vertex selected. Also, the "+" button seems don't have the metaphor of "save", though you can select some nodes and use the "+" to save them directly - I keeped this feature for usability - but it shouldn't exist......

I will consider this anyway. Appreciate for your code-testing and UX advices (●'◡'●)
