### ISSUE TITLE
Geo Nodes Group Input and output is detached

### ISSUE THREAD

**Issue by zuppasoupnikmat** [Trantor2098/hot_node#8]
i dont know if this probably outside of the scope of this addon, but is it possible to save the whole "geometry nodes" (alongside the group input and output) ?

example of the issues :
![image](https://github.com/user-attachments/assets/0860b749-349e-4152-98b7-7b326f19750a)
the group input is not attached to anything

The original :
![image](https://github.com/user-attachments/assets/33af8f94-72ec-42e5-bc4b-42fc58dcde8e)

*project file is using this .blend file https://ko-fi.com/s/7015cfa07c

**Comment by Trantor2098** [comment]
Hi zuppasoupnikmat, it is possible. Just turn on the "Overwrite Tree I/O" at the add-on panel's extended menu:
![Screenshot 2024-11-12 190858](https://github.com/user-attachments/assets/5ced646e-917a-4ae1-b6ce-91f4e4cff2f4)
The the Group I/Os will be modified by your preset.

It's off by default because we need to prevent the Group I/O from being changed when the user already set the I/Os.

Welcome to comment again if you have any other questions :)

**Comment by zuppasoupnikmat** [comment]
Thank you ! i tried with the overwrite I/O , and now its instantly crash on vanilla 4.2.3, i guess the node setup is too weird / have lots of dependencies on it 
*i attach the .json below in the zip 
[TestPack.zip](https://github.com/user-attachments/files/17739844/TestPack.zip)

**Comment by Trantor2098** [comment]
Oh so sososo sorry, I tested it and it do crashes the blender {{{(>_<)}}}
I will try to fix it and report here if got any progress

**Comment by Trantor2098** [comment]
Reason found. The second socket of your group have an empty name, this crashes blender when getting preset. You can give it a name and reset the preset then it can be got from preset correctly (a warning will be thrown but things just go fine, ignore it. Maybe I can solve this warning in the later addon version).
![image](https://github.com/user-attachments/assets/1fb6c7a0-578b-44a5-889d-56d06211c12e)

I will solve the empty name problem in the next addon version :)

**Comment by Trantor2098** [comment]
Crash risk / useless warning were both solved in the newly released version 0.7.5, you can update it in blender~
Thank you for helping find the crashing risk!!

**Comment by zuppasoupnikmat** [comment]
Thank you very much ! now it works with both when i leave the second socket name empty (end up being UNNAMED) and named. Doesnt crash anymore. 

One last question, i'm sorry this issues i been submit is might be such a niche / wrong way of using the addon, i notice it works nicely when its under group node/ just adding couple node tree (retain all the value) , but in this case it seems the default value is not registered

![image](https://github.com/user-attachments/assets/4f52b477-0a33-4e60-9ac6-bcc3443331ca)

Should i've add additional setup etc for this ?
Thank you so much for your support !

**Comment by Trantor2098** [comment]
Appriciate for the clarity of describe, and dont worry it's ok to post any problem here, welcome to post. (●'◡'●)

Well, it's a add-on limitation, for now I haven't developed a better way to solve that but right-click these slots one by one and choose `Reset to Default` manually... It is indeed a important need of function, but may take some times to solve, I will try to achieve this as soon as possible in the future version.

**Comment by zuppasoupnikmat** [comment]
Thank you very much for your response ! yeah i try pressing Backspace on every coloumn one by one seems to work nicely (except the drop down list option which seems to be blender limitation side of things)
